# Generated by Django 4.1.10 on 2023-09-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('ComputadorId', models.IntegerField(primary_key=True, serialize=False)),
                ('ComputadorSerial', models.IntegerField(blank=True, null=True)),
                ('ComputadorMarca', models.CharField(max_length=50)),
            ],
        ),
    ]
